import { 
  HeartPulse, 
  Brain, 
  Bone, 
  Eye, 
  Cat, 
  Activity, 
  Leaf, 
  Thermometer, 
  Layers, 
  Crosshair, 
  Stethoscope, 
  Droplets, 
  Smile,
  Zap,
  Microscope,
  Stethoscope as Steth
} from 'lucide-react';

export const specialties = [
  { name: 'Acupuntura', slug: 'acupuntura', icon: Leaf },
  { name: 'Cardiologia', slug: 'cardiologia', icon: HeartPulse },
  { name: 'Cirurgia', slug: 'cirurgia', icon: Crosshair },
  { name: 'Dermatologia', slug: 'dermatologia', icon: Layers },
  { name: 'Endocrinologia', slug: 'endocrinologia', icon: Droplets },
  { name: 'Felinos', slug: 'felinos', icon: Cat },
  { name: 'Gastroenterologia', slug: 'gastroenterologia', icon: Activity },
  { name: 'Hematologia', slug: 'hematologia', icon: Droplets },
  { name: 'Nefrologia', slug: 'nefrologia', icon: Activity },
  { name: 'Neurologia', slug: 'neurologia', icon: Brain },
  { name: 'Nutrologia e Nutrição', slug: 'nutricao', icon: Smile },
  { name: 'Odontologia', slug: 'odontologia', icon: Smile },
  { name: 'Oftalmologia', slug: 'oftalmologia', icon: Eye },
  { name: 'Oncologia', slug: 'oncologia', icon: Microscope },
  { name: 'Ortopedia', slug: 'ortopedia', icon: Bone },
  { name: 'Pneumologia', slug: 'pneumologia', icon: Thermometer },
];
